# -*- coding: utf-8 -*-
"""simple_code .py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YjrtRfEnGZzDVPzEANQMc_vUUyN97-dB
"""

team_members = [
    {
        "Name": "Aworetan Olamide",
        "Slack Username": "Olamide_etan",
        "Country": "Nigeria",
        "Hobby": "Swimming",
        "Affiliation": "Kazlat Public Analyst Laboratory",
        "DNA Sequence": "ATGGAGGGCCGCCTAAATTAATTGGGTTAATTTTAAATTGGCCTTGGCCTAT"

    },
    {
        "Name": "Faith Omondi",
        "Slack Username": "Faith",
        "Country": "Kenya",
        "Hobby": "Drawing",
        "Affiliation": "University of Nairobi",
        "DNA Sequence": "AGGTCCGTACTTACGGGTTAATGCGGGATACCACCTTAACCTAATAATATAA"

    },
    {
        "Name": "Shreya Venugopalan Omesh Chendilkumar",
        "Slack Username": "Shreya",
        "Country": "India",
        "Hobby": "Listening to music",
        "Affiliation": "Anna University",
        "DNA Sequence": "ATTAGCCGATGCCGTAATTGGCCAATGGTATTTAATTTTAATTTGGATATAT"

    },
    {
        "Name": "Taiwo Bankole",
        "Slack Username": "Taiwo Bakole",
        "Country": "Nigeria",
        "Hobby": "Reading",
        "Affiliation": "University of Maryland",
        "DNA Sequence": "ACAGCCCACAAATTCCACCTGCCACAGGTTGGCCTGGCTCGACCCAGGTGGTGCCCTGCTTGCTGAGCC"

    },
    {
        "Name": "Adeyeye Daniel",
        "Slack Username": "Adeyeye Daniel",
        "Country": "Nigeria",
        "Hobby": "Writing",
        "Affiliation": "University of Maryland",
        "DNA Sequence": "ATGCGTACGTTAGACCGGATCGTTAAGCCTTAGGCTTATAATTAATTAGGGTCATTAGGCCTCTCTCTGCT"
    },
    {
        "Name": "Ofosaren Favour Oghenevwerhie",
        "Slack Username": "Ofosaren Favour",
        "Country": "Nigeria",
        "Hobby": "Dancing",
        "Affiliation": "Delta State University",
        "DNA Sequence": "ATGCCTCCTGACTTACGGAATACGGAATAA"
    },
    {
        "Name": "Oyiyechukwu Elizabeth Chikelu",
        "Slack Username": "Elizabeth Chikelu",
        "Country": "Nigeria",
        "Hobby": "Writing",
        "Affiliation": "Enugu State University of Science and Technology,Nigeria",
        "DNA Sequence": "AGCTCCCGCCACCCATGGCCATACCGATGCCCCAAAAGCAGGAGGACGC"
    }
]
# print each member's information
print("TEAM MEMBER INFORMATION")
for member in team_members:
    print(f"Name:{member['Name']}")
    print(f"Slack Username:{member['Slack Username']}")
    print(f"Country:{member['Country']}")
    print(f"Hobby:{member['Hobby']}")
    print(f"Affiliation:{member['Affiliation']}")
    print(f"DNA Sequence:{member['DNA Sequence']}")

